env:
  CI: true
  ANDROID_HOME: /usr/local/share/android-sdk/
  PATH: "$PATH:/usr/local/share/android-sdk/platform-tools/"
steps:
  - label: "Android :android:"
    command:
    - "source ~/.bash_profile"
    - "nvm install"
    - "npm install"
    - "npm run clean"
    - "npm run test-js"
    - "npm run test-unit-android -- --release"
    - "npm run test-e2e-android-multi -- --release --headless --verbose --ci"
         
  - label: "IOS :ios:"
    command:
    - "source ~/.bash_profile"
    - "nvm install"
    - "npm install"
    - "npm run clean"
    - "npm run test-unit-ios -- --release"
    - "npm run test-snapshot-ios -- --release"
    - "npm run test-e2e-ios -- --release --multi --ci"
