steps:
  - block: ":rocket: Release!"
    prompt: "Fill out the details for release"
    if: build.message =~ /^release$/i
    fields:
      - select: "RELEASE_BUILD"
        key: "release-build"
        hint: "Latest (true) or Snapshot (false)?"
        default: "true"
        options:
          - label: "True"
            value: true
          - label: "False"
            value: false
      - text: "VERSION"
        key: "version"
      # - text: "NPM_TAG"
      #   key: "npm-tag"
      #   required: false
      - text: "BUILD_DOCUMENTATION_VERSION"
        key: "build-documentation-version"
      - text: "REMOVE_DOCUMENTATION_VERSION"
        key: "remove-documentation-version"
  
  ## Android build is the same for master/branch/PRs/releases
  - label: ":android: Android"
    command:
    - "nvm install"
    - "npm install"
    - "npm run test-js"
    - "npm run test-unit-android -- --release"
    - "npm run test-e2e-android-multi -- --release --headless --verbose --ci"
    key: "android_build"

  - label: ":ios: iOS"
    command:
    - "nvm install"
    - "npm install"
    - "npm run test-unit-ios -- --release"
    - "npm run test-snapshot-ios -- --release"
    - "npm run test-e2e-ios -- --release --multi --ci"
    key: "ios_build"

  - label: ":package: Publish"
    env:
    if: "build.message =~ /^release$/i || build.branch == 'master'"
    command:
    - "nvm install"
    - "npm install"
    - "npm run release"
    depends_on:
    - "android_build"
    - "ios_build"
    agents:
      agent-118: "true"
